requires "CPAN::Meta";
requires "IO::Prompt::Tiny";
requires "Net::GitHub::V3";
requires "Path::Tiny";
requires "RT::Client::REST";
requires "RT::Client::REST::Ticket";
requires "RT::Client::REST::User";
requires "Syntax::Keyword::Junction";
requires "Try::Tiny";
